# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [5]:
# Import your libraries:
import pandas as pd
from sklearn.datasets import load_diabetes

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [86]:
# Your code here:
diabetes = load_diabetes()

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [87]:
# Your code here:
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [80]:
# Your code here:
print(diabetes.DESCR)
#print(diabetes.data)


.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

What are the variables in this dataset according to the description? List them in the markdown cell below

   - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

#### Enter your answer here:

age, sex, body mass index, average blood pressure, s1, s2, s3, s4, s5, s6




Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [9]:
# Your code here:
# Your code here:
diabetes_df = pd.DataFrame(diabetes.data, columns = diabetes.feature_names)
diabetes_df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [83]:
# Your code here:
from sklearn.linear_model import LinearRegression
lr =  LinearRegression()

Initialize the model in the variable `diabetes_model`

In [84]:
# Your code here:
X = diabetes.data
y = diabetes.target

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [85]:
# Your code here:
diabetes_model = lr.fit(X,y)
#print(diabetes_model.keys())
print(f"The intercept is {diabetes_model.intercept_} and the coefficients are {diabetes_model.coef_}")

The intercept is 152.13348416289597 and the coefficients are [ -10.0098663  -239.81564367  519.84592005  324.3846455  -792.17563855
  476.73902101  101.04326794  177.06323767  751.27369956   67.62669218]


# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [89]:
X_train = diabetes_df 
y_train = pd.DataFrame(diabetes.target)

In [23]:
df = pd.concat([X_train, y_train], axis=1)
df = df.rename(columns={0:"target"})
df.sample()

age       sex       bmi       bp        s1       s2        s3  \
91  0.045341 -0.044642  0.051996 -0.05387  0.063101  0.06476 -0.010266   

          s4        s5        s6  target  
91  0.034309  0.037236  0.019633   164.0

In [24]:
import statsmodels.formula.api as smf

In [25]:
results = smf.ols("target ~ age + sex + bmi + bp + s1 + s2 + s3 + s4 + s5 + s6", data = df).fit()
results.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 target   R-squared:                       0.518
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     46.27
Date:                Wed, 01 Mar 2023   Prob (F-statistic):           3.83e-62
Time:                        12:52:38   Log-Likelihood:                -2386.0
No. Observations:                 442   AIC:                             4794.
Df Residuals:                     431   BIC:                             4839.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    152.1335      2.576     59.061      0.000     147.071     157.196
age          -10.0099     59.749     -0.168      0.867    -127.446     107.426
sex         -239.8156     61.222     -3.917      0.000    -360.147    -119.484
bmi          519.8459     66.533      7.813      0.000     389.076     650.616
bp           324.3846     65.422      4.958      0.000     195.799     452.970
s1          -792.1756    416.680     -1.901      0.058   -1611.153      26.802
s2           476.7390    339.030      1.406      0.160    -189.620    1143.098
s3           101.0433    212.531      0.475      0.635    -316.684     518.770
s4           177.0632    161.476      1.097      0.273    -140.315     494.441
s5           751.2737    171.900      4.370      0.000     413.407    1089.140
s6            67.6267     65.984      1.025      0.306     -62.064     197.318
==============================================================================
Omnibus:                        1.506   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.471   Jarque-Bera (JB):                1.404
Skew:                           0.017   Prob(JB):                        0.496
Kurtosis:                       2.726   Cond. No.                         227.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
# H0: coef == 0
# H1: coef != 0
# Those coeficients where p-value > 0.05 we cannot reject H0 and thus do not impact the model. They are:
# age, s1, s2, s3, s4 and s6.

# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [28]:
# Your code here:
auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [29]:
# Your code here:
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [30]:
# Your code here: all of them are numbers
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

What is the newest model year and the oldest model year?

In [31]:
# Your code here:
print(auto["model_year"].max())
print(auto["model_year"].min())

82
70


Check the dataset for missing values and remove all rows containing at least one missing value.

In [32]:
# Your code here:
auto.isna().sum()

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [33]:
auto.dropna(axis=0, how="any", inplace=True)

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [34]:
# Your code here: 5 values
auto.cylinders.value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [35]:
# Import the necessary function
from sklearn.model_selection import train_test_split as tts

auto.drop(columns='car_name', inplace=True)
X = auto.drop("mpg", axis=1) 
y = auto.mpg # target variable

In [36]:
# Your code here:
X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.2)


In [37]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)


(313, 6) (313,) (79, 6) (79,)


Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [90]:
# Your code here:


Next, fit the model in the cell below.

In [38]:
# Your code here:
auto_model = lr.fit(X_train, y_train)
lr.coef_


array([-0.50636911,  0.01227067,  0.00118449, -0.00693213,  0.12350587,
        0.72487065])

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [45]:
# Your code here:
from sklearn import metrics
import numpy as np

y_pred = auto_model.predict(X_test)
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
r2 = metrics.r2_score(y_test, y_pred)

In [46]:
# Import the necessary function:
print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"R2: {r2}")

MAE: 2.9242835794948108
MSE: 13.725033706011276
RMSE: 3.7047312596207673
R2: 0.8206893712429554


#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_train` data and the predicted `y_test_pred`.

In [44]:
# Your code here:
y_test_pred = lr.predict(X_train)
r2_new = metrics.r2_score(y_train, y_test_pred)
print(f"The new r2 of the model is: {r2_new}")

The new r2 of the model is: 0.8042154928601519


# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [47]:
# Your code here:
X_train09, X_test09, y_train09, y_test09 = tts(X, y, test_size = 0.1)



Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [48]:
# Your code here:
auto_model09 = lr.fit(X_train09, y_train09)

Compute the predicted values and r squared score for our new model and new sample data.

In [53]:
# Your code here:
y_pred09 = auto_model09.predict(X_test)
r209 = metrics.r2_score(y_test, y_pred09)
print(f'The r2 of the model is {r209}')


The r2 of the model is 0.826315981180215


Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [56]:
# Your code here:
y_pred09_new = auto_model09.predict(X_test09)
r209_new = metrics.r2_score(y_test09, y_pred09_new)
print(f'The new r2 of the model is {r209_new}') # R2 increased from 0.81 to 0.88, so the new model is slightly better.

The new r2 of the model is 0.8665808058510578


# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [58]:
from sklearn.feature_selection import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [60]:
# Your code here:
selector = RFE(auto_model, n_features_to_select=3)

Fit the model and print the ranking

In [61]:
# Your code here:
selector = selector.fit(X_train, y_train)


In [62]:
selector.support_


array([ True, False, False, False,  True,  True])

In [63]:
selector.ranking_


array([1, 2, 4, 3, 1, 1])

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [64]:
# Your code here:
X_train.sample()

cylinders  displacement  horse_power  weight  acceleration  model_year
302          4         105.0         70.0    2150          14.9          79

In [90]:
auto_model.feature_names_in_

array(['cylinders', 'displacement', 'horse_power', 'weight',
       'acceleration', 'model_year'], dtype=object)

In [93]:
selector.support_

array([ True, False, False, False,  True,  True])

In [96]:
#diabetes_df = pd.DataFrame(selector.support_, columns = auto_model.feature_names_in_)


Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [69]:
mpg = auto[['mpg']]
lr =  LinearRegression()
auto_reduced = auto[['cylinders','acceleration','model_year']]
X_train_reduced, X_test_reduced, y_train_reduced, y_test_reduced = tts(auto_reduced, mpg, test_size = 0.2)
auto_model_reduced = lr
auto_model_reduced.fit(X_train_reduced,y_train_reduced)


LinearRegression()

In [70]:
y_pred_reduced = auto_model_reduced.predict(X_test_reduced)
metrics.r2_score(y_test_reduced, y_pred_reduced)

0.7689104066703136

In [71]:
# Now the r2 is 0.60 which is lower than before. So, no improvement.